[update] version update 9.0.4
SAP/cloud-sdk-ios pull request #35
Opened 2023-02-13 14:18 UTC by VMadiwalkar

2023-02-13 14:51 UTC, MarcoEidinger requested changes
CI error

```
error: checksum of downloaded artifact of binary target 'SAPFiori' 
(0e58fbca9cdf93b8d415c49f4d1deeb58bc0e9ce8c69eb57520a76b6c7fe6a29) does not match checksum specified by the manifest (7ccfb27b419edcec239a973a5ab182c33c14152956bf89bbf787184f7e1fd052)
````

When I run the udpate_version.sh locally for 9.0.4 then I get

```
let sapFioriChecksum = "0e58fbca9cdf93b8d415c49f4d1deeb58bc0e9ce8c69eb57520a76b6c7fe6a29"
```

for Package.swift

Please check

2023-02-14 05:07 UTC, VMadiwalkar commented
Hi @MarcoEidinger

Updated Fiori checksum

2023-02-14 11:13 UTC, MarcoEidinger reviewed
CI build passed and hence mergable. I would have preferred that sheep script gets updated as well to indicate the right maven repository for 9.x

2023-02-14 11:13 UTC, MarcoEidinger approved these changes

2023-02-14 11:41 UTC, merged